apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-kaniko
spec:
  params:
    - name: IMAGE
    - name: GIT_URL
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=Dockerfile
        - --context=$(params.GIT_URL)
        - --destination=$(params.IMAGE)
        - --insecure
        - --skip-tls-verify
