apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: run-build-and-push
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: git-url
      value: https://github.com/YOUR_USERNAME/Markeble
    - name: image-url
      value: docker.io/YOUR_DOCKERHUB_USERNAME/openflights:latest
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 500Mi
