apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
spec:
  params:
    - name: IMAGE
    - name: GIT_URL
  tasks:
    - name: build-push
      taskRef:
        name: build-and-push-kaniko
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: GIT_URL
          value: $(params.GIT_URL)
