version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openflights_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../rails-app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
