apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
spec:
  params:
    - name: git-url
    - name: image-url
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
    - name: kaniko
      runAfter:
        - clone
      taskRef:
        name: kaniko-build
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: $(params.image-url)
