apiVersion: v1
kind: Secret
metadata:
  name: github-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: https://github.com/khaleedo/Markeble
  username: YOUR_GITHUB_USERNAME
  password: YOUR_PERSONAL_ACCESS_TOKEN
